// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: launchpad/project.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Project struct {
	// Project owner
	ProjectOwner string `protobuf:"bytes,1,opt,name=project_owner,json=projectOwner,proto3" json:"project_owner,omitempty" yaml:"project_owner"`
	// Project title
	ProjectTitle string `protobuf:"bytes,2,opt,name=project_title,json=projectTitle,proto3" json:"project_title,omitempty" yaml:"project_title"`
	// Project unique id of each project (incremental from 1)
	ProjectId uint64 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" yaml:"project_id"`
	// Project address to store assets
	ProjectAddress string `protobuf:"bytes,4,opt,name=project_address,json=projectAddress,proto3" json:"project_address,omitempty" yaml:"project_address"`
	// Whether project is already active
	ProjectActive bool `protobuf:"varint,5,opt,name=project_active,json=projectActive,proto3" json:"project_active,omitempty" yaml:"project_active"`
	// Project information
	ProjectInformation string `protobuf:"bytes,6,opt,name=project_information,json=projectInformation,proto3" json:"project_information,omitempty" yaml:"project_information"`
	// Begin time for a project
	StartTime time.Time `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_74080baa240e1b89, []int{0}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Project.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return m.Size()
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetProjectOwner() string {
	if m != nil {
		return m.ProjectOwner
	}
	return ""
}

func (m *Project) GetProjectTitle() string {
	if m != nil {
		return m.ProjectTitle
	}
	return ""
}

func (m *Project) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *Project) GetProjectAddress() string {
	if m != nil {
		return m.ProjectAddress
	}
	return ""
}

func (m *Project) GetProjectActive() bool {
	if m != nil {
		return m.ProjectActive
	}
	return false
}

func (m *Project) GetProjectInformation() string {
	if m != nil {
		return m.ProjectInformation
	}
	return ""
}

func (m *Project) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*Project)(nil), "nghuyenthevinh2000.nebula.launchpad.Project")
}

func init() { proto.RegisterFile("launchpad/project.proto", fileDescriptor_74080baa240e1b89) }

var fileDescriptor_74080baa240e1b89 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcf, 0x6e, 0x94, 0x40,
	0x18, 0xdf, 0xb1, 0xb5, 0x75, 0x47, 0xad, 0x11, 0x5b, 0xa5, 0x24, 0xc2, 0x06, 0x2f, 0x7b, 0x62,
	0xb6, 0xd5, 0x78, 0x30, 0x31, 0xb1, 0x78, 0xf2, 0xd4, 0x86, 0xf4, 0x60, 0xbc, 0x34, 0x03, 0x4c,
	0x61, 0x0c, 0xcc, 0x10, 0x66, 0x58, 0xdd, 0xb7, 0xe8, 0x63, 0xf5, 0xd8, 0xa3, 0x27, 0x34, 0xbb,
	0x0f, 0x60, 0xc2, 0x13, 0x18, 0x66, 0x60, 0x71, 0xd7, 0x78, 0xe3, 0xf7, 0x6f, 0xf8, 0x7e, 0x33,
	0x1f, 0x7c, 0x91, 0xe1, 0x8a, 0x45, 0x69, 0x81, 0x63, 0x54, 0x94, 0xfc, 0x2b, 0x89, 0xa4, 0x57,
	0x94, 0x5c, 0x72, 0xe3, 0x15, 0x4b, 0xd2, 0x6a, 0x41, 0x98, 0x4c, 0xc9, 0x9c, 0xb2, 0xf4, 0x74,
	0x36, 0x9b, 0x79, 0x8c, 0x84, 0x55, 0x86, 0xbd, 0x75, 0xc4, 0xb2, 0x23, 0x2e, 0x72, 0x2e, 0x50,
	0x88, 0x05, 0x41, 0xf3, 0x93, 0x90, 0x48, 0x7c, 0x82, 0x22, 0x4e, 0x99, 0x3e, 0xc4, 0x72, 0x12,
	0xce, 0x93, 0x8c, 0x20, 0x85, 0xc2, 0xea, 0x1a, 0x49, 0x9a, 0x13, 0x21, 0x71, 0x5e, 0x74, 0x86,
	0xe3, 0x6d, 0x03, 0x66, 0x8b, 0x5e, 0xd2, 0x67, 0x5f, 0x29, 0x84, 0x34, 0xe8, 0xa4, 0xc3, 0x84,
	0x27, 0x5c, 0xf3, 0xed, 0x97, 0x66, 0xdd, 0xdf, 0x3b, 0x70, 0xff, 0x42, 0x77, 0x30, 0xde, 0xc3,
	0xc7, 0x5d, 0x9d, 0x2b, 0xfe, 0x8d, 0x91, 0xd2, 0x04, 0x13, 0x30, 0x1d, 0xfb, 0x66, 0x53, 0x3b,
	0x87, 0x0b, 0x9c, 0x67, 0xef, 0xdc, 0x0d, 0xd9, 0x0d, 0x1e, 0x75, 0xf8, 0xbc, 0x85, 0x7f, 0xc7,
	0x25, 0x95, 0x19, 0x31, 0xef, 0xfd, 0x2f, 0xae, 0xe4, 0x21, 0x7e, 0xd9, 0x42, 0xe3, 0x0d, 0x84,
	0xbd, 0x4e, 0x63, 0x73, 0x67, 0x02, 0xa6, 0xbb, 0xfe, 0x51, 0x53, 0x3b, 0x4f, 0x37, 0xb3, 0x34,
	0x76, 0x83, 0x71, 0x07, 0x3e, 0xc5, 0xc6, 0x47, 0xf8, 0xa4, 0x57, 0x70, 0x1c, 0x97, 0x44, 0x08,
	0x73, 0x57, 0xfd, 0xd6, 0x6a, 0x6a, 0xe7, 0xf9, 0x66, 0xb4, 0x33, 0xb8, 0xc1, 0x41, 0xc7, 0x9c,
	0x69, 0xc2, 0xf8, 0x00, 0x0f, 0xd6, 0x9e, 0x48, 0xd2, 0x39, 0x31, 0xef, 0x4f, 0xc0, 0xf4, 0x81,
	0x7f, 0xdc, 0xd4, 0xce, 0xd1, 0xd6, 0x19, 0x4a, 0x77, 0x83, 0xbe, 0xea, 0x99, 0xc2, 0xc6, 0x39,
	0x7c, 0xb6, 0x1e, 0x90, 0x5d, 0xf3, 0x32, 0xc7, 0x92, 0x72, 0x66, 0xee, 0xa9, 0x51, 0xec, 0xa6,
	0x76, 0xac, 0xad, 0x16, 0x83, 0xc9, 0x0d, 0x8c, 0xbe, 0xce, 0x40, 0x1a, 0x9f, 0x21, 0x14, 0x12,
	0x97, 0xed, 0x5d, 0xe5, 0xc4, 0xdc, 0x9f, 0x80, 0xe9, 0xc3, 0x53, 0xcb, 0xd3, 0x0f, 0xef, 0xf5,
	0x0f, 0xef, 0x5d, 0xf6, 0x9b, 0xe1, 0xbf, 0xbc, 0xad, 0x9d, 0xd1, 0x70, 0x5b, 0x43, 0xd6, 0xbd,
	0xf9, 0xe9, 0x80, 0x60, 0xac, 0x88, 0xd6, 0xee, 0x5f, 0xdc, 0x2e, 0x6d, 0x70, 0xb7, 0xb4, 0xc1,
	0xaf, 0xa5, 0x0d, 0x6e, 0x56, 0xf6, 0xe8, 0x6e, 0x65, 0x8f, 0x7e, 0xac, 0xec, 0xd1, 0x97, 0xb7,
	0x09, 0x95, 0x69, 0x15, 0x7a, 0x11, 0xcf, 0xd1, 0xbf, 0x8b, 0x8c, 0xf4, 0x22, 0xa3, 0xef, 0x68,
	0xd8, 0x7e, 0xb9, 0x28, 0x88, 0x08, 0xf7, 0xd4, 0x3c, 0xaf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x34, 0x3f, 0xdb, 0x28, 0x17, 0x03, 0x00, 0x00,
}

func (m *Project) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Project) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Project) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintProject(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	if len(m.ProjectInformation) > 0 {
		i -= len(m.ProjectInformation)
		copy(dAtA[i:], m.ProjectInformation)
		i = encodeVarintProject(dAtA, i, uint64(len(m.ProjectInformation)))
		i--
		dAtA[i] = 0x32
	}
	if m.ProjectActive {
		i--
		if m.ProjectActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.ProjectAddress) > 0 {
		i -= len(m.ProjectAddress)
		copy(dAtA[i:], m.ProjectAddress)
		i = encodeVarintProject(dAtA, i, uint64(len(m.ProjectAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.ProjectId != 0 {
		i = encodeVarintProject(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ProjectTitle) > 0 {
		i -= len(m.ProjectTitle)
		copy(dAtA[i:], m.ProjectTitle)
		i = encodeVarintProject(dAtA, i, uint64(len(m.ProjectTitle)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ProjectOwner) > 0 {
		i -= len(m.ProjectOwner)
		copy(dAtA[i:], m.ProjectOwner)
		i = encodeVarintProject(dAtA, i, uint64(len(m.ProjectOwner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProject(dAtA []byte, offset int, v uint64) int {
	offset -= sovProject(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Project) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProjectOwner)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	l = len(m.ProjectTitle)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	if m.ProjectId != 0 {
		n += 1 + sovProject(uint64(m.ProjectId))
	}
	l = len(m.ProjectAddress)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	if m.ProjectActive {
		n += 2
	}
	l = len(m.ProjectInformation)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovProject(uint64(l))
	return n
}

func sovProject(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProject(x uint64) (n int) {
	return sovProject(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Project) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Project: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Project: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectTitle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectTitle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ProjectActive = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectInformation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectInformation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProject(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProject
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProject
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProject
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProject
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProject
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProject
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProject        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProject          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProject = fmt.Errorf("proto: unexpected end of group")
)
